SELECT F.FARMCODE AS Farmcode,
F.FARM_OWNERID AS OwnerID,
CASE WHEN 
(SELECT OWNER_NAME FROM T_OWNERS_CHGS WHERE OWNER_ID = F.FARM_OWNERID) IS NOT NULL OR 
(SELECT OWNER_NAME FROM T_OWNERS_CHGS WHERE OWNER_ID = F.FARM_OWNERID) <> ''
THEN (SELECT OWNER_NAME FROM T_OWNERS_CHGS WHERE OWNER_ID = F.FARM_OWNERID)
ELSE (SELECT OWNER_NAME FROM T_OWNERS WHERE OWNER_ID = F.FARM_OWNERID)
END OwnerName,
F.FARM_BASE AS "Base/Company",
F.FARM_STATUS AS Status
FROM T_FARMS F JOIN T_OWNERS O
ON F.FARM_OWNERID = O.OWNER_ID
ORDER BY OwnerID
