SELECT M.C_FARMCODE AS FarmCode,
CASE 
WHEN C.ATT_FARM_FieldGrp_CODE IS NULL OR C.ATT_FARM_FieldGrp_CODE = '' THEN M.ATT_FARM_FieldGrp_CODE
ELSE C.ATT_FARM_FieldGrp_CODE
END FieldGrp,
CASE 
WHEN C.ATT_FARM_Base_CODE IS NULL OR C.ATT_FARM_Base_CODE ='' THEN M.ATT_FARM_Base_CODE
ELSE C.ATT_FARM_Base_CODE
END Base,
CASE
WHEN C.ATT_FARM_FarmSuit_CODE IS NULL OR C.ATT_FARM_FarmSuit_CODE = '' THEN M.ATT_FARM_FarmSuit_CODE
ELSE C.ATT_FARM_FarmSuit_CODE
END Status,
CASE
WHEN C.I_OWNER_ID IS NULL OR C.I_OWNER_ID = '' THEN M.I_OWNER_ID
ELSE C.I_OWNER_ID
END OwnerID,
CASE 
WHEN C.I_OWNER_ID IS NULL OR C.I_OWNER_ID = '' THEN (SELECT C_OWNER_NAME FROM T_OWNERS WHERE I_OWNER_ID = M.I_OWNER_ID)
ELSE (SELECT C_OWNER_NAME FROM T_OWNERS WHERE I_OWNER_ID = C.I_OWNER_ID)
END OwnerName
FROM T_FARMS M LEFT JOIN T_FARM_CHGS C
ON M.C_FARMCODE = C.C_FARMCODE
