SELECT M.C_FARMCODE,
CASE C.ATT_FARM_FieldGrp_CODE
WHEN NULL THEN M.ATT_FARM_FieldGrp_CODE 
ELSE C.ATT_FARM_FieldGrp_CODE
END FieldGrp
FROM T_MASTER M LEFT JOIN T_FARM_CHGS C ON
M.C_FARMCODE = C.C_FARMCODE